---

ann_model_params: {'epochs': 5, #5000,
                   'batch_size': 64,
                   'shuffle': True,
                   'initialiser': 'normal',
                   'activation_funct': 'relu',
                   'loss_funct': "logcosh",
                   'default_learning_rate': 1e-3,
                   'optimisation_metric': 'mae',
                   'early_stopping_verbose': 1,
                   'model_fit_verbose': 0,
                   'use_multiprocessing': True,
                   'validation_split': 0.1,
                   'validation_freq': 1,
                   'patience': 100,
                   'mode': 'auto',
                   'monitor': 'val_loss',
                  }

lstm_model_params: {'epochs': 5, #5000,
                     'batch_size': 32,
                     'shuffle': True,
                     'activation_funct': 'relu',
                     'loss_funct': "logcosh",
                     'default_learning_rate': 1e-3,
                     'optimisation_metric': 'mae',
                     'early_stopping_verbose': 1,
                     'model_fit_verbose': 0,
                     'validation_split': 0.1,
                     'validation_freq': 1,
                     'patience': 100,
                     'mode': 'auto',
                     'monitor': 'val_loss',
                    }

lstm_2_model_params: {'epochs': 5, #5000,
                      'batch_size': 32,
                      'shuffle': True,
                      'activation_funct': 'relu',
                      'loss_funct': "logcosh",
                      'default_learning_rate': 1e-3,
                      'optimisation_metric': 'mae',
                      'early_stopping_verbose': 1,
                      'model_fit_verbose': 0,
                      'validation_split': 0.1,
                      'validation_freq': 1,
                      'patience': 100,
                      'mode': 'auto',
                      'monitor': 'val_loss',
                     }

sann_model_params: {'num_models': 5,
                    'batch_size': 64,
                    'epochs_sub_model': 5, #1000,
                    'epochs_ensemble': 5, #1000,
                    'model_fit_verbose': 0,
                    'shuffle': True,
                    'default_learning_rate': 1e-3,
                    'initialiser': 'normal',
                    'activation_funct': 'relu',
                    'loss_funct': 'logcosh',
                    'optimisation_metric': 'mae',
                    'scoring_metric_1': 'r2',
                    'scoring_metric_2': 'neg_mean_squared_error',
                    'scoring_metric_3': 'neg_mean_absolute_error',
                   }

sann_2_model_params: {'num_models': 5,
                      'batch_size': 64,
                      'epochs_sub_model': 5, #1000,
                      'epochs_ensemble': 5, #1000,
                      'model_fit_verbose': 0,
                      'shuffle': True,
                      'default_learning_rate': 1e-3,
                      'initialiser': 'normal',
                      'activation_funct': 'relu',
                      'loss_funct': 'logcosh',
                      'optimisation_metric': 'mae',
                      'scoring_metric_1': 'r2',
                      'scoring_metric_2': 'neg_mean_squared_error',
                      'scoring_metric_3': 'neg_mean_absolute_error',
                     }

svm_model_params: {'kernel': 'rbf',
                   'C': 5, #10000,
                   'model_fit_verbose': True,
                  }
